import "./scss/globals.scss";

export const metadata = {
  title: "the circl studio",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/logos/infinity.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
